version: 2
updates:
  # Fetch and update latest `devcontainers` pkgs
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: maintenance/update-packages
    labels:
      - dependencies
    open-pull-requests-limit: 10
    reviewers:
      - halceyon
    assignees:
      - halceyon
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    target-branch: maintenance/update-packages
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10
    reviewers:
      - halceyon
    assignees:
      - halceyon
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `cargo` packages
  - package-ecosystem: cargo
    directory: "/src-tauri"
    schedule:
      interval: daily
      time: "00:00"
    target-branch: maintenance/update-packages
    labels:
      - dependencies
      - cargo
    open-pull-requests-limit: 10
    reviewers:
      - halceyon
    assignees:
      - halceyon
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    target-branch: maintenance/update-packages
    labels:
      - dependencies
    open-pull-requests-limit: 10
    reviewers:
      - halceyon
    assignees:
      - halceyon
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
